services:

  wordpress:
    image: wordpress:latest
    container_name: wordpress
    restart: always
    healthcheck:
      test: ["CMD", "curl", "--fail", "http://localhost:80"]
      interval: 60s
      retries: 5
      start_period: 20s
      timeout: 10s
    depends_on:
      mysql:
        condition: service_healthy
    ports:
      - 8800:80
      - 4433:443
    environment:
      WORDPRESS_DB_HOST: mysql
      WORDPRESS_DB_USER: wp-user
      WORDPRESS_DB_PASSWORD: wordpress
      WORDPRESS_DB_NAME: wordpress_esgi
    volumes:
      - wordpress:/var/www/html
    networks:
      - backnet
      - bdd
      - frontnet

  mysql:
    image: mysql:latest
    container_name: mysql
    restart: always
    healthcheck:
      test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost"]
      timeout: 20s
      retries: 10
    ports:
      - 3306:3306
    environment:
      MYSQL_DATABASE: wordpress_esgi
      MYSQL_USER: wp-user
      MYSQL_PASSWORD: wordpress
      MYSQL_RANDOM_ROOT_PASSWORD: '1'
    volumes:
      - mysql:/var/lib/mysql
    networks:
      - bdd

  nginx:
    image: jc21/nginx-proxy-manager:latest
    restart: always
    healthcheck:
      test: ["CMD", "curl", "--fail", "http://localhost:81"]
      interval: 60s
      retries: 5
      start_period: 20s
      timeout: 10s
    ports:
      - 8008:80
      - 4443:443
      - 8181:81
    volumes:
      - nginx-data:/data
      - nginx-tls:/etc/letsencrypt
    networks:
      - frontnet

volumes:
  wordpress:
  mysql:
  nginx-data:
  nginx-tls:

networks:
  bdd:
  frontnet:
  backnet:
